// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djagtpvhvxzzyrniwdyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqYWd0cHZodnh6enlybml3ZHlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDM0NTgsImV4cCI6MjA2MDU3OTQ1OH0.jpWYrWPE84wl23U7Y2C3G2dw9zo4MX6To_W7foG7BlM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);